### ISSUE TITLE
NoMethodError: undefined method `post' for Net::HTTP:Class

### ISSUE THREAD

**Issue by icattlecoder** [nervosnetwork/ckb-demo-ruby-sdk#14]
```
[2] pry(main)> miner.get_balance
NoMethodError: undefined method `post' for Net::HTTP:Class
from /Users/zakj/projects/ckb-demo-ruby-sdk/lib/ckb/api.rb:19:in `rpc_request'
```
Maybe I used a mismatched http lib, so what version of ruby should I use?

**Comment by rainchen** [comment]
`Net::HTTP.post` method is required by ruby 2.4+, try to use ruby 2.4+

**Comment by ashchan** [comment]
Ruby 2.3 will be history soon. I believe we're safe to revert this and require ruby 2.4+.

**Comment by doitian** [comment]
Or we can put this into a monkey patch file and only include it in Ruby 2.3

**Comment by doitian** [comment]
The macOS bundled Ruby is still 2.3

**Comment by ashchan** [comment]
> The macOS bundled Ruby is still 2.3

> uby 2.3 is now under the state of the security maintenance phase, until the end of March of 2019. After that date, maintenance of Ruby 2.3 will be ended. We recommend you start planning the migration to newer versions of Ruby, such as 2.5 or 2.4.

Source: [Ruby 2.3.8 Released](https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-3-8-released/).
