### ISSUE TITLE
Avoid using `<>` in shell command placeholders

### ISSUE THREAD

**Issue by kaikai1024** [nervosnetwork/ckb-demo-ruby-sdk#33]
I don't know  how to run this: ` ./target/debug/ckb-binary-to-script < <path to argv_source_entry> > <path to processed_argv_source_entry> ` when i follow the steps of [install mruby contract](https://github.com/nervosnetwork/ckb-demo-ruby-sdk#install-mruby-contract)

**Comment by kaikai1024** [comment]
ooo, It's the redirect symbol.

**Comment by doitian** [comment]
I think it is a bit confused here since `<>` are also used to surround the token.
